Ctrl.cache("Gameboy.Tetris",function(){var r=K.object("Gameboy.Tetris"),k,d={},n,p,q,l,o;n={BOMB:1,DECREASEGUN:2,INCREASEGUN:3,ACROSSMOUSE:4};k=K.clazz({map:[],ctor:function(a){var b=this;if(a)b.map=a;else{a=Math.floor(b.list.length*Math.random());b.$listIndex=a;b.map=b.list[a]}},rotate:function(a){var b=this,c=0,f=Gameboy.GameKeys;if(b.list){if(a==f.RIGHT){if(b.$listIndex+1<b.list.length)c=b.$listIndex+1}else if(a==f.LEFT)c=b.$listIndex-1<0?b.list.length-1:b.$listIndex-1;b.map=b.list[c];b.$listIndex=
c}},getRotateMap:function(a){var b=this,c=0,f=Gameboy.GameKeys;if(b.list){if(a==f.RIGHT){if(b.$listIndex+1<b.list.length)c=b.$listIndex+1}else if(a==f.LEFT)c=b.$listIndex-1<0?b.list.length-1:b.$listIndex-1;return b.list[c]}return K.clone(b.map)},setColorType:function(a){this.colorType=a}});d.IBlock=K.clazz(k,function(a){var b=[[[0],[1,1,1,1]],[[0,1],[0,1],[0,1],[0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.TBlock=K.clazz(k,function(a){var b=[[[0,1],[1,1,1]],[[1],[1,1],[1]],
[[1,1,1],[0,1]],[[0,1],[1,1],[0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.LLBlock=K.clazz(k,function(a){var b=[[[1],[1,1,1]],[[1,1],[1],[1]],[[1,1,1],[0,0,1]],[[0,1],[0,1],[1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.RLBlock=K.clazz(k,function(a){var b=[[[1,1,1],[1]],[[1,1],[0,1],[0,1]],[[0,0,1],[1,1,1]],[[1],[1],[1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.LZBlock=K.clazz(k,function(a){var b=[[[1],[1,1],[0,1]],[[0,1,1],[1,
1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.RZBlock=K.clazz(k,function(a){var b=[[[0,1],[1,1],[1]],[[1,1],[0,1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.DBlock=K.clazz(k,function(a){return{ctor:function(b){a.ctor.call(this,b||[[1,1],[1,1]])}}});d.OBlock=K.clazz(d.DBlock,function(a){return{ctor:function(){a.ctor.call(this,[[0],[0,1]])}}});d.$2IBlock=K.clazz(k,function(a){var b=[[[0],[0,1,1]],[[0],[0,1],[0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,
c)}}});d.$3IBlock=K.clazz(k,function(a){var b=[[[0],[1,1,1]],[[0,1],[0,1],[0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.$LLBlock=K.clazz(k,function(a){var b=[[[1],[1,1]],[[1,1],[1]],[[1,1],[0,1]],[[0,1],[1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.$RLBlock=K.clazz(k,function(a){var b=[[[1,1],[1]],[[1,1],[0,1]],[[0,1],[1,1]],[[1],[1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.$$Block=K.clazz(k,function(a){var b=[[[1,0,1],[0,1,
0],[1,0,1],[0]],[[0,1],[1,0,1],[0,1],[0]],[[0,1],[0,1],[1,0,1],[0,1]],[[0,1],[1,0,1,1],[0,1]],[[0,1],[1,0,1],[0,1],[0,1]],[[0,0,1],[1,1,0,1],[0,0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.FBlock=K.clazz(k,function(a){var b=[[[1,0,0,0,1],[0,1,0,1],[0,0,1]],[[0,0,1],[0,1],[1],[0,1],[0,0,1]],[[0,0,1],[0,1,0,1],[1,0,0,0,1]],[[1],[0,1],[0,0,1],[0,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.BTBlock=K.clazz(k,function(a){var b=[[[1,1,1],[0,1],[0,1]],[[0,
0,1],[1,1,1],[0,0,1]],[[0,1],[0,1],[1,1,1]],[[1],[1,1,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.BLZBlock=K.clazz(k,function(a){var b=[[[1,1],[0,1],[0,1,1]],[[0,0,1],[1,1,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.BRZBlock=K.clazz(k,function(a){var b=[[[0,1,1],[0,1],[1,1]],[[1],[1,1,1],[0,0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.UBlock=K.clazz(k,function(a){var b=[[[1,0,1],[1,1,1]],[[1,1],[1,0],[1,1]],[[1,1,1],[1,
0,1]],[[1,1],[0,1],[1,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.CSBlock=K.clazz(k,function(a){var b=[[[0,1],[1,1,1],[0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.LDOBlock=K.clazz(k,function(a){var b=[[[0,1],[0,1,1],[1,1]],[[1],[1,1,1],[0,1]],[[0,1,1],[1,1],[0,1]],[[0,1],[1,1,1],[0,0,1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.RDOBlock=K.clazz(k,function(a){var b=[[[1,1],[0,1,1],[0,1]],[[0,0,1],[1,1,1],[0,1]],[[0,1],[1,1],[0,1,
1]],[[0,1],[1,1,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.DDBlock=K.clazz(k,function(a){var b=[[[1],[0,1,1],[0,1,1]],[[0,0,1],[1,1],[1,1]],[[1,1],[1,1],[0,0,1]],[[0,1,1],[0,1,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.ODBlock=K.clazz(k,function(a){var b=[[[1],[0,1,1],[0,1]],[[0,0,1],[1,1],[0,1]],[[0,1],[1,1],[0,0,1]],[[0,1],[0,1,1],[1]]];return{ctor:function(c){this.list=b;a.ctor.call(this,c)}}});d.BombBlock=K.clazz(k,function(a){return{ctor:function(){var b=
this;b.isSpecial=true;b.specialType=n.BOMB;a.ctor.call(b,[[0,0,0,0,0,0],[0,1,0,0,1,0],[0,0,1,1,0,0],[0,0,1,1,0,0],[0,0,0,0,0,0]])}}});d.DecreaseGunBlock=K.clazz(k,function(a){return{ctor:function(){var b=this;b.isSpecial=true;b.specialType=n.DECREASEGUN;a.ctor.call(b,[[0,1],[0,1]])}}});d.IncreaseGunBlock=K.clazz(k,function(a){return{ctor:function(){var b=this;b.isSpecial=true;b.specialType=n.INCREASEGUN;a.ctor.call(b,[[0,1],[0,1],[0,1]])}}});d.AcrossMouseBlock=K.clazz(k,function(a){return{ctor:function(){var b=
this;b.isSpecial=true;b.specialType=n.ACROSSMOUSE;a.ctor.call(b,[[0],[0,1]])}}});d.ActiveBlock=K.clazz({x:0,y:0,width:0,height:0,offsetLeft:0,offsetTop:0,offsetRight:0,maxLength:0,bottomPoints:[],leftPoints:[],rightPoints:[],_calcVars:function(){var a=this;a.width=0;a.height=0;a.offsetLeft=0;a.offsetTop=0;a.offsetRight=0;a.bottomPoints=[];a.leftPoints=[];a.rightPoints=[];for(var b=[],c,f,e,g=0,h=0,i=a.map.length,j=0;j<i;j++){c=b[j]=0;f=false;a.leftPoints[j]=null;a.rightPoints[j]=null;for(var m=0,
s=a.map[j].length;m<s;m++){a.bottomPoints[m]||(a.bottomPoints[m]=null);if(a.map[j][m]==0&&!f)b[j]++;else if(a.map[j][m]){c=m;a.rightPoints[j]={x:m,y:j};if(!f){e=f=true;g++;a.leftPoints[j]={x:m,y:j}}a.bottomPoints[m]={x:m,y:j}}}e||a.offsetTop++;a.width=Math.max(a.width,s);h=Math.max(h,c+1)}a.offsetRight=a.width-h;a.offsetLeft=Math.min.apply(null,b);a.height=g},ctor:function(a,b){var c=this;c.map=a.map;c.$bk=a;c.colorType=c.$bk.colorType;c.specialType=c.$bk.specialType;c.isSpecial=!!c.$bk.isSpecial;
c._calcVars();c.y=-(c.height+c.offsetTop);c.maxLength=Math.max(c.width,c.map.length);c.x=Math.floor((b-c.width)/2)},rotate:function(a){this.$bk.rotate(a);this.map=this.$bk.map;this._calcVars()},getRotatedVars:function(a){var b={};b.width=0;b.height=0;b.offsetLeft=0;b.offsetTop=0;for(var c=[],f,e,g=0,h=a.length,i=0;i<h;i++){f=c[i]=0;e=false;for(var j=0,m=a[i].length;j<m;j++)if(a[i][j]==0&&!e)c[i]++;else if(a[i][j]){f=j;if(!e){e=true;g++}}e||b.offsetTop++;b.width=Math.max(b.width,f+1)}b.offsetLeft=
Math.min.apply(null,c);b.height=g;return b},getRotateMap:function(a){a=this.$bk.getRotateMap(a);return{map:a,rotatedVars:this.getRotatedVars(a)}}});p={color:0,blocks:[[d.IBlock,d.TBlock,d.LZBlock,d.RZBlock,d.DBlock,d.FBlock,d.OBlock],[d.$2IBlock,d.$3IBlock,d.$LLBlock,d.BRZBlock,d.BLZBlock,d.IBlock,d.BTBlock,d.TBlock,d.LZBlock,d.BRZBlock,d.BLZBlock,d.RZBlock,d.DBlock,d.OBlock,d.BRZBlock,d.BLZBlock,d.DDBlock,d.BTBlock],[d.$2IBlock,d.$3IBlock,d.$LLBlock,d.BRZBlock,d.BLZBlock,d.IBlock,d.BombBlock,d.BTBlock,
d.TBlock,d.LZBlock,d.IncreaseGunBlock,d.BRZBlock,d.FBlock,d.BLZBlock,d.DecreaseGunBlock,d.RZBlock,d.DBlock,d.OBlock,d.BRZBlock,d.BLZBlock,d.DDBlock,d.BTBlock,d.AcrossMouseBlock],[d.AcrossMouseBlock,d.IBlock,d.TBlock,d.LLBlock,d.ODBlock,d.RLBlock,d.BombBlock,d.LZBlock,d.RZBlock,d.DBlock,d.OBlock,d.BombBlock,d.$2IBlock,d.$3IBlock,d.$LLBlock,d.DecreaseGunBlock,d.$RLBlock,d.BTBlock,d.$$Block,d.FBlock,d.BombBlock,d.BRZBlock,d.BLZBlock,d.ODBlock,d.UBlock,d.CSBlock,d.LDOBlock,d.RDOBlock,d.BombBlock,d.AcrossMouseBlock,
d.IncreaseGunBlock,d.DDBlock]],list:[],getBlock:function(){var a=this,b=Math.floor(Math.random()*(a.list.length-1));b=new a.list[b];b.isSpecial?b.setColorType(l.cfg.special):b.setColorType(1+Math.floor(Math.random()*a.color));return b},nextBlock:function(){var a=this;a.$lastBlock=a.getBlock();return a.$lastBlock},getNext:function(){var a=this;if(!a.$lastBlock)return a.nextBlock();return a.$lastBlock},setBlockIndex:function(a){this.list=this.blocks[a]},getCount:function(){return this.blocks.length}};
o={START:"sounds/tetris/start.mp3",MOVE:"sounds/tetris/move.mp3",DOWN:"sounds/tetris/down.mp3",ROTATE:"sounds/tetris/rotate.mp3",DISLINE:"sounds/tetris/disline.mp3",BOMB:"sounds/tetris/bomb.mp3",SHOOT:"sounds/tetris/shoot.mp3",OVER:"sounds/tetris/over.mp3"};q={activeBlockId:"_active_block",lineScoreMap:{"1":100,"2":400,"3":900,"4":1500},speedUpScore:1E3,waitTime:200,prepareAll:function(){var a=this;a.stopFastDown();a.removeActiveBlock();a.$isDrawOver=false;a.chgActiveBlock(p.getNext());a.drawNext(p.nextBlock());
a.drawActiveBlock();a.updateActiveBlockPos()},resetSpeed:function(a){var b=this;b.pause();b.$timer=K.timer(b.doDown,a,true,b)},doDown:function(){var a=this;if(!a.autoDown())if(!a.$isDrawOver&&a.$acb.y+a.$acb.offsetTop+a.$acb.height<=0)a.over();else if(!a.$acb.isSpecial||a.$acb.specialDid>=2)a.prepareAll()},updateScore:function(a){var b=this;if(!b.$scoreK)b.$scoreK={score:0};b.$scoreK[a]||(b.$scoreK[a]=0);b.$scoreK[a]++;b.$scoreK.score+=b.lineScoreMap[a];l.core.updateScoreAndSpeed(b.$scoreK.score,
b.speedUpScore)},chgActiveBlock:function(a){this.$acb=new d.ActiveBlock(a,this.stageSize[0])},drawActiveBlock:function(){var a=this,b=a.activeBlockId,c;if(!a.$isDrawOver){if(a.$acb.y>=0)a.$isDrawOver=true;if(!K(b)){var f=K("div",{id:b},{position:"absolute"});document.body.appendChild(f);l.mapMgr.drawMap({id:b,size:[a.$acb.maxLength,a.$acb.maxLength]})}f=a.$acb.map;for(var e=l.cfg,g=0,h=f.length;g<h;g++)if(g+a.$acb.y>=0)for(var i=0,j=f[g].length;i<j;i++)if(f[g][i]==1&&(c=K(K.strFormat(e.cellIdFormat,
b,g,i))))c.className=K.strFormat(e.highLightCellClass,a.$acb.colorType)}},drawSpecialBomb:function(){for(var a=this,b=a.$acb.map,c,f=l.cfg,e=0,g=b.length;e<g;e++)if(e+a.$acb.y>=0)for(var h=-a.$acb.x,i=b[e].length;h<i;h++)if(h+a.$acb.x<a.stageSize[0]&&e+a.$acb.y<a.stageSize[1])if(c=K(K.strFormat(f.cellIdFormat,a.activeBlockId,e,h)))c.className=f.specialUsedCellClass},removeActiveBlock:function(){K.nodeDel(this.activeBlockId)},updateActiveBlockPos:function(){var a=this,b={x:a.$acb.x*a.blockCellSize.width+
a.stageBound.x,y:a.$acb.y*a.blockCellSize.height+a.stageBound.y};K.nodeStyle(a.activeBlockId,{left:b.x+"px",top:b.y+"px"})},autoDown:function(){var a=this;if(a.canDown()){a.$acb.y++;a.drawActiveBlock();a.updateActiveBlockPos();return true}a.putActiveBlock();return false},putActiveBlock:function(a){var b=this,c=b.$acb.map,f=n,e,g=-1;e=-1;if(b.$acb.isSpecial){if(!b.$acb.specialDid)b.$acb.specialDid=0;b.$acb.specialDid++;if(b.$acb.specialType==f.BOMB)if(b.$acb.specialDid==1){b.$wait=true;b.resetSpeed(b.waitTime);
b.drawSpecialBomb();l.soundPlayer.play5(o.BOMB);a=0;for(var h=c.length;a<h;a++){f=b.$acb.y+a;if(f>=0&&f<b.stageSize[1]){for(var i=0,j=c[a].length;i<j;i++){e=b.$acb.x+i;if(e>=0&&e<b.stageSize[0])b.mainMap[f][e]=0}if(g==-1)g=f;e=f}}b.$acb.y=b.stageSize[1];b.$isDrawOver=true}else{delete b.$wait;b.startFastDown()}else if(b.$acb.specialType==f.DECREASEGUN){if(a){c=b.$acb.x+b.$acb.bottomPoints[1].x;a=b.$acb.offsetTop+b.$acb.height+b.$acb.y-1;if(a<b.stageSize[1])for(a=a;a<b.stageSize[1];a++)if(a+1<b.stageSize[1])if((!b.mainMap[a]||
b.mainMap[a][c]==0)&&b.mainMap[a+1][c]!=0){g=e=b.mainMap[a+1][c]=0;break}}b.$acb.specialDid=3}else if(b.$acb.specialType==f.INCREASEGUN){if(a){c=b.$acb.x+b.$acb.bottomPoints[1].x;a=b.$acb.offsetTop+b.$acb.height+b.$acb.y;if(a<b.stageSize[1])for(a=a;a<b.stageSize[1];a++)if(a+1<b.stageSize[1])if(b.mainMap[a][c]==0){if(b.mainMap[a+1][c]!=0){b.mainMap[a][c]=l.cfg.defaultColor;g=e=a;break}}else break;else{b.mainMap[a][c]=l.cfg.defaultColor;g=e=a}}b.$acb.specialDid=3}else if(b.$acb.specialType==f.ACROSSMOUSE){for(a=
0;a<c.length;a++){f=b.$acb.y+a;if(f>=0&&f<b.stageSize[1]){for(h=0;h<c[a].length;h++)if(c[a][h]!=0){e=b.$acb.x+h;if(e>=0&&e<b.stageSize[0]&&b.mainMap[f][e]==0)b.mainMap[f][e]=l.cfg.defaultColor}if(g==-1)g=f;e=f}}b.$acb.specialDid++}}else for(a=0;a<c.length;a++){f=b.$acb.y+a;if(f>=0&&f<b.stageSize[1]){for(h=0;h<c[a].length;h++)if(c[a][h]==1){e=b.$acb.x+h;if(e>=0&&e<b.stageSize[0])b.mainMap[f][e]=b.$acb.colorType}if(g==-1)g=f;e=f}}if(g>=0&&e>=0){b.clearSolidLines(g,e);l.mapMgr.updateStage()}},clearSolidLines:function(a,
b){for(var c=this,f=c.mainMap,e=0,g=a;g<=b;g++){a=true;for(var h=0,i=f[g].length;h<i;h++)if(f[g][h]==0){a=false;break}if(a){e++;c.mainMap.splice(g,1);g--;b--}}if(e>0){l.soundPlayer.play4(o.DISLINE);c.updateScore(e);for(f=0;f<e;f++){b=[];for(a=0;a<c.stageSize[0];a++)b.push(0);c.mainMap.unshift(b)}}else if(c.$acb)c.$acb.isSpecial&&(c.$acb.specialType==n.INCREASEGUN||c.$acb.specialType==n.DECREASEGUN)?l.soundPlayer.play4(o.SHOOT):l.soundPlayer.play4(o.DOWN);return e},canDown:function(){var a=this,b=
true;if(a.$acb.y+a.$acb.height+a.$offsetTop>=a.stageSize[1])return false;var c,f,e;if(a.$acb.isSpecial&&a.$acb.specialType==n.ACROSSMOUSE){c=a.$acb.x+a.$acb.bottomPoints[1].x;var g=a.$acb.offsetTop+a.$acb.height+a.$acb.y;f=true;if(g<a.stageSize[1])for(g=g;g<a.stageSize[1];g++)if(a.mainMap[g][c]==0){f=false;break}if(f){if(!a.$acb.specialDid)a.$acb.specialDid=0;a.$acb.specialDid+=2;b=false}}else{g=0;for(var h=a.$acb.bottomPoints.length;g<h;g++)if(c=a.$acb.bottomPoints[g]){if(a.$acb.y<0&&c.y+a.$acb.y+
1>=0){f=c.x+a.$acb.x;e=a.$acb.y+c.y+1}else if(a.$acb.y>=0){f=c.x+a.$acb.x;e=a.$acb.y+c.y+1}if(f<a.stageSize[0]&&e<a.stageSize[1]){if(a.mainMap[e][f]!=0){b=false;break}}else if(e>=a.stageSize[1]-1){b=false;break}}}return b},canRotate:function(a){var b=this,c,f,e;if(a.rotatedVars.offsetLeft+b.$acb.x<0)b.$acb.x=a.rotatedVars.offsetLeft;else if(a.rotatedVars.width+b.$acb.x>b.stageSize[0])b.$acb.x=b.stageSize[0]-a.rotatedVars.width;e=a.map;for(var g=0,h=e.length;g<h;g++){f=b.$acb.y+g;if(f>=0&&f<b.stageSize[1])for(var i=
0,j=e[g].length;i<j;i++)if(e[g][i]==1){a=b.$acb.x+i;if(a>=0&&a<b.stageSize[0]&&b.mainMap[f][a]!=0){c=true;break}}if(c)break}return!c},clearActiveBlock:function(){for(var a=this,b=a.$acb.map,c,f=l.cfg,e=0,g=b.length;e<g;e++)if(e+a.$acb.y>=0)for(var h=0,i=b[e].length;h<i;h++)if(b[e][h]==1&&(c=K(K.strFormat(f.cellIdFormat,a.activeBlockId,e,h))))c.className=f.normalCellClass;a.$isDrawOver=false},rotateBlock:function(){var a=this;if(a.$acb.isSpecial)a.$acb.specialType!=n.ACROSSMOUSE&&a.putActiveBlock(true);
else if(a.canRotate(a.$acb.getRotateMap(a.rotateDirection))){a.clearActiveBlock();a.$acb.rotate(a.rotateDirection);a.drawActiveBlock();a.updateActiveBlockPos()}},moveActiveBlockTo:function(a){var b=this,c=Gameboy.GameKeys,f=true,e,g,h=n;if(!(b.$acb.isSpecial&&b.$acb.specialType==h.BOMB&&b.$acb.specialDid>=1))if(a==c.LEFT){if(b.$acb.x+b.$acb.offsetLeft>0){if(b.$acb.specialType==h.ACROSSMOUSE){e=b.$acb.x+b.$acb.bottomPoints[1].x;g=b.$acb.offsetTop+b.$acb.height+b.$acb.y-1;c=true;if(g>=0){for(a=0;a<
e;a++)if(b.mainMap[g][a]==0){c=false;break}if(c)f=false}}else{a=0;for(h=b.$acb.leftPoints.length;a<h;a++)if(c=b.$acb.leftPoints[a]){if(b.$acb.y<0&&a+b.$acb.y>=0){e=b.$acb.x+c.x-1;g=b.$acb.y+a}else if(b.$acb.y>=0){e=b.$acb.x+c.x-1;g=b.$acb.y+c.y}if(e>=0&&b.mainMap[g][e]!=0){f=false;break}}}if(f){b.$acb.x--;b.updateActiveBlockPos()}}}else if(a==c.RIGHT)if(b.$acb.x+b.$acb.width-b.$acb.offsetRight<b.stageSize[0]){if(b.$acb.specialType==h.ACROSSMOUSE){e=b.$acb.x+b.$acb.bottomPoints[1].x;g=b.$acb.offsetTop+
b.$acb.height+b.$acb.y-1;c=true;if(g>=0){for(a=e;a<b.stageSize[0];a++)if(b.mainMap[g][a]==0){c=false;break}if(c)f=false}}else{a=0;for(h=b.$acb.rightPoints.length;a<h;a++)if(c=b.$acb.rightPoints[a]){if(b.$acb.y<0&&a+b.$acb.y>=0){e=b.$acb.x+c.x+1;g=b.$acb.y+a}else if(b.$acb.y>=0){e=b.$acb.x+c.x+1;g=b.$acb.y+c.y}if(e>=0&&b.mainMap[g][e]!=0){f=false;break}}}if(f){b.$acb.x++;b.updateActiveBlockPos()}}},startFastDown:function(){this.resetSpeed(l.cfg.fastSpeed)},stopFastDown:function(){this.resetSpeed(l.cfg.speed)},
start:function(){var a=this;a.prepareAll();a.gon()},gon:function(){this.stopFastDown()},pause:function(){K.clsTimer(this.$timer)},over:function(){var a=this;a.pause();l.soundPlayer.play1(o.OVER);l.mapMgr.resetNext();l.core.showGameOver()},drawNext:function(a){var b=this,c=l.mapMgr;b.$lastNextBlockMap&&c.clearNext(b.$lastNextBlockMap);b.$lastNextBlockMap=a.map;c.drawNext(b.$lastNextBlockMap,a.colorType)},receiveKey:function(a){if(!this.$wait){var b=this,c=Gameboy.GameKeys;if(a==c.START){l.soundPlayer.play1(o.START);
b.start()}else if(a==c.PAUSE)b.pause();else if(a==c.GON)b.gon();else if(a==c.UP){b.$acb&&!b.$acb.isSpecial&&l.soundPlayer.play2(o.ROTATE);b.rotateBlock()}else if(a==c.DOWN){if(!b.$isFastDown){b.doDown();b.$isFastDown=true;b.startFastDown()}}else if(a==c.LEFT||a==c.RIGHT){l.soundPlayer.play3(o.MOVE);b.moveActiveBlockTo(a)}else if(a==c.DOWNRELEASE)if(b.$isFastDown){b.$isFastDown=false;b.stopFastDown()}}},init:function(){var a=this,b=l.mapMgr,c=l.cfg,f=0.4;a.stageSize=b.stageSize;a.mainMap=b.mainMap;
a.stageBound=b.stageBound;a.blockCellSize=b.cellSize;p.color=c.maxColor;a.rotateDirection=c.rotateDirection;for(var e=0,g=a.mainMap.length-1;e<c.startLevel;e++,g--)for(var h=0,i=a.mainMap[g].length,j,m;h<i;h++){j=Math.random();m=Math.floor((1-j)*c.maxColor);a.mainMap[g][h]=j<f?0:m+Math.floor(Math.random()*(c.maxColor-m))+1}a.clearSolidLines(g,a.mainMap.length-1);b.updateStage()}};K.mix(r,Gameboy.AbstractGame);K.mix(r,{name:"Tetris",innerGameCount:p.getCount(),init:function(a){l=a;q.init()},setInnerGameIndex:function(a){p.setBlockIndex(a)},
receiveKey:function(a){q.receiveKey(a)},updateSpeed:function(a){q.resetSpeed(a)}})});
