Ctrl.cache("Gameboy",function(){var q=K.object("Gameboy"),i,p,c,r,j,k,u,s,v,l,n,w;i={UP:1,DOWN:2,LEFT:3,RIGHT:4,ROTATE:5,START:6,PAUSE:7,STARTORPUASE:8,DOWNRELEASE:9,LEFTRELEASE:10,RIGHTRELEASE:11,UPRELEASE:12,GON:13,CHANGESPEED:14};p={PLAY:1,PAUSE:2,OVER:3};c={stageId:"main",nextId:"next",templetId:"gameboy_temp",mapBlock:"map_temp",cellTagName:"td",cellIdFormat:"{0}_cell_{1}_{2}",highLightCellClass:"main_cell_on_{0}",normalCellClass:"main_cell",scoreId:"score",specialCellClass:"main_cell_on_special",
specialUsedCellClass:"main_cell_on_specialed",numberBlock:"number_temp",speedId:"speed",speedBlock:"speed_temp",speedIdFormat:"_speed_{0}",speedOnClass:"spdcur",startLevelId:"startlevel",maxColor:7,special:"special",specialUsed:"specialed",defaultColor:8,defaultStartSpeedLevel:1,defaultStartLevel:0,rotateLeft1Class:"rtal",rotateRight1Class:"rtar",rotateLeft2Class:"rtal1",rotateRight2Class:"rtar1",rotateId:"rotate",gameStatus:p.OVER,curGame:null,curGameCount:-1,gameCount:-1,speed:1500,speedLevel:1,
maxLevel:10,startLevel:0,rotateDirection:i.RIGHT,speedMap:{"1":1500,"2":1200,"3":1E3,"4":900,"5":800,"6":700,"7":600,"8":500,"9":400,"10":300},fastSpeed:20};w=K.clazz({ctor:function(){var a=this;a.id="sp_"+K.id();a.embed()},embed:function(){var a='<object clsid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" height="1" width="1" type="application/x-shockwave-flash" id="{id}" name="{id}"  data="sounds/ap2.swf"><param name="allowScriptAccess" value="always"><param name="allowNetworking" value="all"><param name="flashvars" value="bufferseconds=1&waitbufferseconds=60"><param name="movie" value="sounds/ap2.swf"></object>';
K(this.id)&&K.nodeDel(this.id);var b=K("div",{});for(K.nodeVal(b,K.strFormat(a,{id:this.id}));b.firstChild;)document.body.appendChild(b.firstChild)},play:function(a){var b=this,d=K(b.id);K.clsTimer(b.$playTimer);b.$playTimer=K.timer(function(){try{d.mpSetURL(a);d.mpPlay()}catch(e){K.log("play ex",e)}})}});l={getPlayer:function(a){var b=this;a="$po"+a;b[a]||(b[a]=new w);return b[a]},play1:function(a){this.getPlayer(1).play(a)},play2:function(a){this.getPlayer(2).play(a)},play3:function(a){this.getPlayer(3).play(a)},
play4:function(a){this.getPlayer(4).play(a)},play5:function(a){this.getPlayer(5).play(a)}};r={keyInterval:90,UP:38,NUM8:104,LEFT:37,NUM4:100,RIGHT:39,NUM6:102,DOWN:40,NUM2:98,ENTER:13,SPACE:32,CTRL:17,init:function(a){a=this;a.$keyTimers={};a.$keyFireTimes={};K.mix(a,K.Evt);K.on(window,"blur",function(){a.stopAllFire()}).on(document,"keydown",function(b,d){if(b=K.evt(b)){K.evtStop(b);d=b.keyCode;switch(d){case a.UP:case a.NUM8:a.startFireKey(i.UP);break;case a.LEFT:case a.NUM4:a.startFireKey(i.LEFT);
break;case a.RIGHT:case a.NUM6:a.startFireKey(i.RIGHT);break;case a.DOWN:case a.NUM2:case a.SPACE:a.startFireKey(i.DOWN);break;case a.ENTER:a.fireKey(i.STARTORPUASE);break;case a.CTRL:a.fireKey(i.CHANGESPEED);break}}}).on(document,"keyup",function(b,d){if(b=K.evt(b)){K.evtStop(b);d=b.keyCode;switch(d){case a.UP:a.stopFireKey(i.UP);a.fireKey(i.UPRELEASE);break;case a.LEFT:a.stopFireKey(i.LEFT);a.fireKey(i.LEFTRELEASE);break;case a.RIGHT:a.stopFireKey(i.RIGHT);a.fireKey(i.RIGHTRELEASE);break;case a.DOWN:case a.NUM2:case a.SPACE:a.stopFireKey(i.DOWN);
a.fireKey(i.DOWNRELEASE);break}}})},startFireKey:function(a){var b=this;if(!b.$keyTimers[a]){b.$keyFireTimes[a]=0;b.$keyTimers[a]=K.timer(function(){b.fireKey(a);b.$keyFireTimes[a]++},b.keyInterval,true)}},stopFireKey:function(a){var b=this;b.$keyFireTimes[a]||b.fireKey(a);K.clsTimer(b.$keyTimers[a]);delete b.$keyTimers[a];delete b.$keyFireTimes[a]},stopAllFire:function(){var a=this;for(var b in a.$keyTimers)a.stopFireKey(b)},fireKey:function(a){this.fireEvt("keychg",{key:a})}};j={stageSize:[11,20],
nextSize:[6,6],cellSize:null,stageBound:null,mainMap:null,init:function(a){var b=this;b.clearStage();b.drawMap({id:c.stageId,size:b.stageSize});b.drawMap({id:c.nextId,size:b.nextSize});b.stageBound=K.nodeBound(c.stageId);b.cellSize=K.nodeBound(K.tags(c.cellTagName,c.stageId)[0]);if(a){b.setStage(a);b.updateStage()}},drawMap:function(a){K.TP.using(c.templetId,c.mapBlock).toFill(a.id,{size:a.size,id:a.id})},drawNext:function(a,b){for(var d=0,e=a.length;d<e;d++)for(var f=0,h=a[d].length;f<h;f++)if(a[d][f]!=
0)K(K.strFormat(c.cellIdFormat,c.nextId,d,f)).className=K.strFormat(c.highLightCellClass,b)},clearNext:function(a){for(var b=0,d=a.length;b<d;b++)for(var e=0,f=a[b].length;e<f;e++)if(a[b][e]!=0)K(K.strFormat(c.cellIdFormat,c.nextId,b,e)).className=c.normalCellClass},resetNext:function(){for(var a=this,b=0,d=a.nextSize[1];b<d;b++)for(var e=0,f=a.nextSize[0];e<f;e++)K(K.strFormat(c.cellIdFormat,c.nextId,b,e)).className=c.normalCellClass},setStage:function(a){this.mainMap=a},updateStage:function(){for(var a=
this,b,d,e=0;e<a.stageSize[1];e++)for(var f=0;f<a.stageSize[0];f++){b=K(K.strFormat(c.cellIdFormat,c.stageId,e,f));if(a.mainMap[e][f]!=0){d=K.strFormat(c.highLightCellClass,a.mainMap[e][f]);if(b.className!=d)b.className=d}else if(b.className!=c.normalCellClass)b.className=c.normalCellClass}},clearStage:function(){var a=this;a.mainMap=[];for(var b=0;b<a.stageSize[1];b++){a.mainMap[b]=[];for(var d=0;d<a.stageSize[0];d++)a.mainMap[b][d]=0}},clearStageCell:function(a,b){var d=this,e=K(K.strFormat(c.cellIdFormat,
c.stageId,a,b));d.mainMap[a][b]=0;if(e.className!=c.normalCellClass)e.className=c.normalCellClass},highLightStageCell:function(a,b,d){var e=this,f=K(K.strFormat(c.cellIdFormat,c.stageId,a,b));e.mainMap[a][b]=d||c.defaultColor;a=K.strFormat(c.highLightCellClass,e.mainMap[a][b]);if(f.className!=a)f.className=a}};k={init:function(a){K.TP.using(c.templetId,c.speedBlock).toFill(c.speedId,{speed:a});K.nodeDel("_loadingpanel").nodeStyle("_mainpanel",{display:""})},drawScore:function(a){K.TP.using(c.templetId,
c.numberBlock).toFill(c.scoreId,{number:a})},drawSpeed:function(a){var b=this;if(b.$lastSpeed)K(K.strFormat(c.speedIdFormat,b.$lastSpeed)).className="";b.$lastSpeed=a;K(K.strFormat(c.speedIdFormat,a)).className=c.speedOnClass},drawStartLevel:function(a){K.TP.using(c.templetId,c.numberBlock).toFill(c.startLevelId,{number:a})},drawRotateDirection:function(a){var b={};b=a==i.RIGHT?{l:c.rotateLeft1Class,r:c.rotateRight1Class}:{l:c.rotateLeft2Class,r:c.rotateRight2Class};K.tags("a",c.rotateId,function(d,
e){d.className=e==1?b.r:b.l})}};u={_map:{"0":[[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,0,0,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]],"1":[[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1]],"2":[[1,1,1,1],[0,0,0,1],[0,0,0,1],[1,1,1,1],[1,0,0,0],[1,0,0,0],[1,1,1,1]],"3":[[1,1,1,1],[0,0,0,1],[0,0,0,1],[1,1,1,1],[0,0,0,1],[0,0,0,1],[1,1,1,1]],"4":[[1,0,0,1],[1,0,0,1],[1,0,0,1],[1,1,1,1],[0,0,0,1],[0,0,0,1],[0,0,0,1]],"5":[[1,1,1,1],[1,0,0,0],[1,0,0,0],[1,1,1,1],[0,0,0,1],[0,0,0,1],[1,1,1,1]],"6":[[1,
1,1,1],[1,0,0,0],[1,0,0,0],[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]],"7":[[1,1,1,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1],[0,0,0,1]],"8":[[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]],"9":[[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1],[0,0,0,1],[0,0,0,1],[1,1,1,1]]},getCode:function(a,b){var d=[],e=this,f,h,m,o=[];if(b<10){f=e._map["0"];h=e._map[b]}else{b+="";var g=0;for(b=b.split("");g<b.length;g++)if(g==0)f=e._map[b[g]];else h=e._map[b[g]]}g=0;for(b=f.length;g<b;g++){d[g]=
[];e=0;for(var t=f[g].length;e<t;e++)d[g].push(f[g][e]?c.defaultColor:0);e=0;for(t=h[g].length;e<t;e++){e||d[g].push(0);d[g].push(h[g][e]?c.defaultColor:0)}if(!g)m=d[g].length}f=d.length;e=Math.floor((a[1]-f)/2);h=Math.floor((a[0]-m)/2);for(g=0;g<a[1];g++){o[g]=[];for(b=0;b<a[0];b++)if(g>=e&&g<e+f)b>=h&&b<h+m?o[g].push(d[g-e][b-h]):o[g].push(0);else o[g].push(0)}return o}};s={list:["Gameboy.Snake","Gameboy.AvoidPlane","Gameboy.Tetris"],listMap:{},load:function(a){for(var b=this,d=0,e,f=0,h=0,m;h<
b.list.length;h++){m=b.list[h];Ctrl.using(m,function(){if(e=b.getGameByIndex(d)){f+=e.innerGameCount;b.listMap[d]=f;d++;d==b.list.length&&K.isFn(a)&&a(f)}else b.list.splice(d,1)})}},getGameByCount:function(a){for(var b=this,d=b.list.length,e=0,f=a,h=0;h<d;h++)if(a<b.listMap[h]){e=h;break}if(h)f-=b.listMap[h-1];return{game:b.getGameByIndex(e),subIndex:f}},getGameByIndex:function(a){var b=this;if(a=b.list[a])return K.object(K.strSwap(a,/\.source$/),true);return q.AbstractGame}};n={CHGGAME:"sounds/sys/game.mp3",
CHGSPEED:"sounds/sys/speed.mp3",CHGLEVEL:"sounds/sys/level.mp3",CHGRATOTE:"sounds/sys/rotate.mp3"};v={init:function(){try{document.execCommand("BackgroundImageCache",false,true)}catch(a){}var b=this;s.load(function(d){k.init(c.maxLevel);c.gameCount=d;r.init();r.onkeychg=function(e){b.sendKey(e.key)};j.init();b.showCurSpeedLevel();b.sendKey(i.RIGHT,true);k.drawRotateDirection(c.rotateDirection)})},sendKey:function(a,b){var d=this,e=p,f=i,h=j;if(c.gameStatus==e.OVER){if(c.$sgo){d.stopShowGameOver();
d.showGameScreen()}if(a==f.LEFT||a==f.RIGHT){if(a==f.RIGHT)if(c.curGameCount+1<c.gameCount)c.curGameCount++;else c.curGameCount=0;else if(c.curGameCount-1>=0)c.curGameCount--;else c.curGameCount=c.gameCount-1;b||l.play1(n.CHGGAME);d.showGameScreen();a=s.getGameByCount(c.curGameCount);c.curGame=a.game;c.curGame.setInnerGameIndex(a.subIndex)}else if(a==f.STARTORPUASE){d.updateScore(0);h.clearStage();h.updateStage();c.gameStatus=e.PLAY;c.curGame.init({uiMgr:k,core:d,mapMgr:j,cfg:c,soundPlayer:l});c.curGame.receiveKey(f.START)}else if(a==
f.DOWN){l.play1(n.CHGLEVEL);c.startLevel++;if(c.startLevel>c.maxLevel)c.startLevel=c.defaultStartLevel;k.drawStartLevel(c.startLevel)}else if(a==f.CHANGESPEED){l.play1(n.CHGSPEED);c.speedLevel++;if(c.speedLevel>c.maxLevel)c.speedLevel=c.defaultStartSpeedLevel;c.speed=c.speedMap[c.speedLevel];d.showCurSpeedLevel()}else if(a==f.UP){l.play1(n.CHGRATOTE);c.rotateDirection=c.rotateDirection==f.LEFT?f.RIGHT:f.LEFT;k.drawRotateDirection(c.rotateDirection)}}else if(c.gameStatus==e.PLAY)if(a==f.STARTORPUASE){c.gameStatus=
e.PAUSE;c.curGame.receiveKey(f.PAUSE)}else c.curGame.receiveKey(a);else if(c.gameStatus==e.PAUSE)if(a==f.STARTORPUASE){c.gameStatus=e.PLAY;c.curGame.receiveKey(f.GON)}},showGameScreen:function(){j.setStage(u.getCode(j.stageSize,c.curGameCount+1));j.updateStage()},updateScoreAndSpeed:function(a,b){this.updateScore(a);this.updateSpeed(a,b)},updateScore:function(a){k.drawScore(a)},showCurSpeedLevel:function(){k.drawSpeed(c.speedLevel)},updateSpeed:function(a,b){var d=c;a=Math.floor(a/b)+1;if(d.speedLevel!=
a&&a<=d.maxLevel&&a>d.speedLevel){d.speed=d.speedMap[d.speedLevel=a];c.curGame.updateSpeed(d.speed)}this.showCurSpeedLevel()},resetSpeedAndLevel:function(){var a=c;a.startLevel=c.defaultStartLevel;a.speedLevel=c.defaultStartSpeedLevel;a.speed=a.speedMap[a.speedLevel];this.showCurSpeedLevel();k.drawStartLevel(a.startLevel)},stopShowGameOver:function(){K.clsTimer(c.$sgo);delete c.$sgo},showGameOver:function(){var a=this,b=j.stageSize[1]-1,d;a.resetSpeedAndLevel();c.gameStatus=p.OVER;a.stopShowGameOver();
c.$sgo=K.timer(function(){for(var e=0;e<j.stageSize[0];e++)j.mainMap[b][e]=d?0:c.defaultColor;j.updateStage();if(d)b++;else b--;if(b==-1){b=0;d=true}if(d&&b>=j.stageSize[1]){a.stopShowGameOver();a.showGameScreen()}},20,1)}};q.AbstractGame={receiveKey:K.fn,setInnerGameIndex:K.fn,updateSpeed:K.fn,innerGameCount:0,init:K.noop};K.mix(q,{GameKeys:i});v.init()});
