Ctrl.cache("Gameboy.Snake",function(){var l=K.object("Gameboy.Snake"),k,f,h=Gameboy.GameKeys,e=h,g,j;g={defaultSnake:[[0,2],[0,1],[0,0]],defaultLife:4,defaultFoodColor:0,maxFoodColor:0,nextLifeWiat4:200,eatOneScore:10,upLevelScore:100};j={START:"sounds/snake/start.mp3",ROUND:"sounds/snake/round.mp3",EAT:"sounds/snake/eat.mp3",BOMB:"sounds/snake/bomb.mp3",OVER:"sounds/snake/over.mp3"};k={snakeDir:e.RIGHT,snakeColor:0,life:g.defaultLife,init:function(){var a=this;a.clear();a.initStartMapAndUI()},getLifeMap:function(){for(var a=
[],b=0;b<g.defaultLife+1-this.life;b++)a[b]=[];for(b=g.defaultLife+1-this.life;b<g.defaultLife+1;b++)a[b]=[0,1];return a},drawLife:function(){f.mapMgr.resetNext();f.mapMgr.drawNext(this.getLifeMap(),f.cfg.defaultColor)},generateSnakeColor:function(){return 1+Math.floor(Math.random()*g.maxFoodColor)},generateBar:function(a,b){a=Math.floor(a*1.5);for(b=0;b<a;){for(var c=this,d=c.generatePos();c.mainMap[d[0]][d[1]];)d=c.generatePos();c.mainMap[d[0]][d[1]]=f.cfg.defaultColor;b++}},generatePos:function(){return[Math.floor(Math.random()*
(this.mainMap.length-1)),Math.floor(Math.random()*(this.mainMap[0].length-1))]},generateFood:function(){for(var a=this,b=a.generatePos(),c;a.mainMap[b[0]][b[1]];)b=a.generatePos();a.foodPos=b;c=a.mainMap[b[0]][b[1]]=1+Math.floor(Math.random()*g.maxFoodColor);if(c==a.snakeColor)a.mainMap[b[0]][b[1]]=g.defaultFoodColor},clear:function(){f.mapMgr.clearStage();this.$snake=K.clone(g.defaultSnake);this.mainMap=f.mapMgr.mainMap;this.snakeDir=e.RIGHT;delete this.$dir},initStartMapAndUI:function(){this.snakeColor=
this.generateSnakeColor();this.generateFood();this.generateBar(f.cfg.startLevel);this.applySnakeToStage();this.drawLife()},applySnakeToStage:function(){for(var a=this,b=a.$snake,c=0,d=b.length,i;c<d;c++){i=b[c];a.mainMap[i[0]][i[1]]=c?a.snakeColor:f.cfg.special}f.mapMgr.updateStage()},moveTo:function(a){var b=this,c=b.getDir(),d=null;if(c==e.RIGHT){if(a[1]<b.mainMap[0].length-1)d=[a[0],a[1]+1]}else if(c==e.DOWN){if(a[0]<b.mainMap.length-1)d=[a[0]+1,a[1]]}else if(c==e.LEFT){if(a[1]>0)d=[a[0],a[1]-
1]}else if(c==e.UP)if(a[0]>0)d=[a[0]-1,a[1]];if(d&&b.mainMap[d[0]][d[1]]&&!K.equal(d,b.foodPos))d=null;return d},updateStage:function(){var a=this,b=a.$snake,c=b[0],d;if(c=a.moveTo(c)){if(K.equal(a.foodPos,c)){a.snakeColor=a.mainMap[c[0]][c[1]];delete a.foodPos;a.updateScore();f.soundPlayer.play3(j.EAT)}else d=b.pop();b.unshift(c);if(d)a.mainMap[d[0]][d[1]]=0;a.applySnakeToStage();a.foodPos||a.generateFood()}else{a.$tempOver=true;a.pause();a.drawSnakeDie();f.soundPlayer.play1(j.BOMB);K.timer(function(){a.clear();
if(a.life){a.life--;a.initStartMapAndUI();a.start()}else a.over();delete a.$tempOver},g.nextLifeWiat4)}},updateScore:function(){if(!this.$score)this.$score=0;this.$score+=g.eatOneScore;f.core.updateScoreAndSpeed(this.$score,g.upLevelScore)},drawSnakeDie:function(){var a=this;a=a.$snake;for(var b=f.mapMgr,c=0,d=a.length,i;c<d;c++){i=a[c];b.highLightStageCell(i[0],i[1],f.cfg.specialUsed)}},setDir:function(a){var b=this;if(!b.$dir)b.$dir=[];b.$dir.push(a);f.soundPlayer.play4(j.ROUND)},getDir:function(){var a=
this;if(a.$dir&&a.$dir.length)return a.snakeDir=a.$dir.shift();return this.snakeDir},lastDir:function(){var a=this;if(a.$dir&&a.$dir.length)return a.$dir[a.$dir.length-1];return a.snakeDir},pause:function(){K.clsTimer(this.$timer);delete this.$timer},resetSpeed:function(a){var b=this;b.pause();b.$timer=K.timer(b.updateStage,a/2,1,b)},start:function(){this.resetSpeed(f.cfg.speed)},startFastDown:function(){this.resetSpeed(f.cfg.fastSpeed*2)},stopFastDown:function(){this.resetSpeed(f.cfg.speed)},over:function(){this.pause();
f.core.showGameOver();f.soundPlayer.play1(j.OVER);this.life=g.defaultLife;delete this.$score},startFast:function(){if(!this.$isFast){this.updateStage();this.$isFast=true;this.startFastDown()}},stopFast:function(){if(this.$isFast){delete this.$isFast;this.stopFastDown()}},receiveKey:function(a){var b=this,c,d;if(!b.$tempOver){c=b.lastDir();d=b.$dir&&!b.$dir.length;if(a==h.LEFT){if(c!=e.RIGHT)if(b.snakeDir==e.LEFT&&d)b.startFast();else c!=e.LEFT&&b.setDir(e.LEFT)}else if(a==h.LEFTRELEASE)b.snakeDir==
e.LEFT&&b.stopFast();else if(a==h.RIGHT){if(c!=e.LEFT)if(b.snakeDir==e.RIGHT&&d)b.startFast();else c!=e.RIGHT&&b.setDir(e.RIGHT)}else if(a==h.RIGHTRELEASE)b.snakeDir==e.RIGHT&&b.stopFast();else if(a==h.DOWN){if(c!=e.UP)if(b.snakeDir==e.DOWN&&d)b.startFast();else c!=e.DOWN&&b.setDir(e.DOWN)}else if(a==h.DOWNRELEASE)b.snakeDir==e.DOWN&&b.stopFast();else if(a==h.UP){if(c!=e.DOWN)if(b.snakeDir==e.UP&&d)b.startFast();else c!=e.UP&&b.setDir(e.UP)}else if(a==h.UPRELEASE)b.snakeDir==e.UP&&b.stopFast();else if(a==
h.START||a==h.GON){f.soundPlayer.play1(j.START);b.start()}else a==h.PAUSE&&b.pause()}}};K.mix(l,Gameboy.AbstractGame);K.mix(l,{name:"Snake",innerGameCount:1,init:function(a){f=a;g.defaultFoodColor=a.cfg.maxColor;g.maxFoodColor=g.defaultFoodColor-1;k.init()},setInnerGameIndex:function(){},receiveKey:function(a){k.receiveKey(a)},updateSpeed:function(a){k.resetSpeed(a)}})});
