Ctrl.cache("K",function(){var l=window,i="length",L="object",G,p=l.document,X=RegExp,P="head",w,aa=["mousemove","touchmove"],Q=["mouseup","touchend"],e,B;function q(a){return(a+"").toLowerCase()}var R="value",C="prototype",j=null;function r(a,b,c,d,f,g){f=H.call(arguments,4);a=m(a)?a:o;d=d||this;b=b||8;g=function(){a.apply(d,f)};return c?l.setInterval(g,b):l.setTimeout(g,b)}function D(a){l.clearTimeout(a);l.clearInterval(a)}var k=true,s=false,S="_$_",T=[],M;function N(a,b,c){if(L==typeof b||m(b)){for(c=
a[i]-2;c>=0;c-=2)if(a[c]==b)return a[c+1];a.push(b,b=e.clone(b,a))}return b}var ba,ca,U,da=/^[\s\xa0\u3000\uFEFF]+|[\s\xa0\u3000\uFEFF]+$/g;function y(a,b){if(a=e.evt(a)){b=e.evtPageXY(a);ea&&fa(I,a,b.x-Y.x,b.y-Y.y,b);O(a)}}function E(a,b){b=(a=e.evt(a))&&a.touches||[];if(!b[i]){e.un(l,"blur",E).un(p,aa,y).un(p,Q,E).un(I,"losecapture",E).un(p,"keydown",O);Q.f&&I.releaseCapture();m(Z)&&Z(I,a);G=I=j}}function J(){return(new Date).getTime()}function na(a,b,c,d){return c*a/d+b}var $,Y,ea,fa,Z,I,V=!!l.getComputedStyle;
function O(a,b){e.evtPrevent(a,b);e.evtCancel(a,b)}function K(a,b,c){a=a||p;b=a.documentElement;c=a.body;B=a.compatMode=="CSS1Compat"?b:c;return{scrollX:b.scrollLeft||c.scrollLeft,scrollY:b.scrollTop||c.scrollTop,left:B.clientLeft,top:B.clientTop}}var oa=J(),ga=(V?"css":"style")+"Float",ha,ia;function t(a,b){return(b=typeof a)==L?a==j&&j+""||q(pa.call(a).slice(8,-1)):b}function u(a,b,c,d,f,g){g=m(c);a||(a=v(b)?[]:{});for(f in b)if(d=g?c(b[f],f,a):k)a[f]=b[f];return a}function ja(){}var ka=l.XMLHttpRequest,
pa=Object[C].toString,H=Array[C].slice;function m(a){return t(a)==qa}function v(a){return t(a)==ra}function A(a){return a&&a[i]&&t(a)!=la&&!a.nodeType}function o(){}var x="on",W={},qa=t(q),ra=t(T),la=t(C),sa=t(da),ta;e=function(a,b,c,d){if(typeof a!=L)a=(d||p)[b||c?"createElement":"getElementById"](a);b&&e.nodeAttr(a,b);c&&e.nodeStyle(a,c);return a};u(e,{e:x,fn:o,type:t,mix:u,stopDrag:E,now:J,evtHalt:O,evtStop:O,isArr:v,isFn:m,timer:r,clsTimer:D,strTrim:function(a,b){return e.strSwap(a,b||da)},strSize:function(a){return e.strSwap(a,
/[^\x00-\xff]/g,x)[i]},strCode:function(a,b){return l[(b?"de":"en")+"codeURIComponent"](a+"")},strSwap:function(a,b,c,d,f,g){a+="";f=-1;g=arguments[i]==2;if(v(b))for(d=v(c);++f<b[i];)a=a.replace(b[f],d&&f<c[i]?c[f]:g?"":c);else a=a.replace(b,g?"":c);return a},strFormat:function(a,b,c){a+="";c=e.isObj(b)?b:H.call(arguments,1);return a=a.replace(/{(\w+)}/g,function(d,f){return c[f]})},strHTML:function(a,b){return e.strSwap(a,b?[/&lt;/g,/&gt;/g,/&quot;/g,/&amp;/g]:[/&/g,/"/g,/</g,/>/g],b?["<",">",'"',
"&"]:["&amp;","&quot;","&lt;","&gt;"])},log:function(){var a=l.console,b=arguments;if(a&&a.log)a.log.apply?a.log.apply(a,b):a.log(H.call(b))},logTime:function(a){if(q[a]){e.log(a+":"+(J()-q[a])+"ms");delete q[a]}else q[a]=J()},isInsof:function(a,b,c){try{c=a instanceof b}catch(d){}return c},isUndef:function(a){return a===ta},isObj:function(a){return t(a)==L},isStr:function(a){return t(a)==la},isReg:function(a){return t(a)==sa},id:function(){return"K"+oa++},test:function(){for(var a=arguments,b=0,
c=a[i];b<c;b++)try{a[b]();return a[b]}catch(d){e.log("K.test",d)}return o},clone:function(a,b,c,d){b||(b=[]);if(!a||!m(a)&&typeof a!=L)return a;else if(a[d="cloneNode"])return a[d](k);else c=m(a)?(new Function("return "+a))():(d=a.constructor,c=new d(a.valueOf()),a==c)?new d:c;b.push(a,c);for(d in a)if(W.hasOwnProperty.call(a,d))c[d]=N(b,a[d]);return c},clsPage:function(){$?e.test($):($=e.test(function(){l.getSelection().removeAllRanges()},function(){p.selection.empty()},function(){p.selection=j}))},
equal:function(a,b,c,d,f){if(a===b)return k;if(v(a)&&v(b)&&(f=a[i])==b[i]){for(d=0;d<f;d++)if(!e.equal(a[d],b[d],c))return s;return k}return c?a==b:a===b},bind:function(a,b,c){c=H.call(arguments,2);a=m(a)?a:o;return function(){return a.apply(b||this,c.concat(H.call(arguments)))}},body:function(a,b){b=K(a);return u({pageWidth:B.scrollWidth,pageHeight:Math.max(B.scrollHeight,B.clientHeight),viewWidth:B.clientWidth,viewHeight:B.clientHeight},b)},clazz:function(a,b,c,d,f){c=function(){var g=this,h,n=
arguments,F=n.callee[C];for(h in F)m(F[h])||(g[h]=e.clone(F[h]));return g.ctor.apply(g,n)};d=m(a)?(f=ja[C]=a[C],new ja):u({},f=a);if(m(b))b=b(f,d,c,a);b&&u(d,b);d.ctor=d.ctor||o;d.constructor=c;c[C]=d;return c},object:function(a,b,c,d,f){c=c||l;a=(a+"").split(".");for(d=0;d<a[i];d++){f=a[d];if(!c[f]){if(b){c=j;break}c[f]={}}c=c[f]}return c},tags:function(a,b,c,d,f,g,h,n,F){f=e(b)||p;d=[];if(f.getElementsByTagName){a=v(a)?a:[a];h=-1;F=m(c);a:for(;a[++h];){g=f.getElementsByTagName(a[h]);if(F||a[i]>
1)for(n=-1;g[++n];)try{(F?c(g[n]):d)&&d.push(g[n])}catch(ma){if(ma==x)break a;e.log(ma,c,g[n])}else d=g}}return d},Evt:{fireEvt:function(a,b,c,d,f,g){d=this;a=q(a);b||(b={});b.sender=d;b.type=a;if(v(f=d[f=S+a]))for(g=0;f[g];g++)try{f[g](b,d)}catch(h){if(h==x)break;e.log("fireEvt:",h,f[g])}m(d[f=x+a])&&d[f](b,d);c&&d.clsEvt(a)},on:function(a,b,c,d){c=this;for(a=e.isArr(a)?a:[a];a[i];){d=q(a.pop());(c[d=S+d]||(c[d]=[])).push(b)}return c},un:function(a,b){for(a=e.isArr(a)?a:[a];a[i];)e.arrRemove(this[S+
q(a.pop())],b);return this},clsEvt:function(a,b){b=this;a=q(a);delete b[S+a];delete b[x+a]}}});u(e,{arrFind:function(a,b,c,d){c=-1;if(v(a))for(d=0;d<a[i];d++)if(e.equal(a[d],b)){c=d;break}return c},arrRemove:function(a,b,c){c=e.arrFind(a,b);c>-1&&a.splice(c,1);return a},arrInsert:function(a,b,c){if(v(a))a.splice(isNaN(c)?a[i]:c,0,b);return a},nodeAttr:function(a,b,c,d,f){if(e.isStr(b)){d=(a=e(a))?a.getAttribute(b):j;c&&a&&a.removeAttribute(b);return d}a=A(a)?a:[a];for(c=a[i];c--;)if(f=e(a[c]))for(d in b)f.setAttribute(d,
b[d]);return e},nodeDoc:function(a){return(a=e(a))&&(a.ownerDocument||a.document)||j},nodeBound:function(a,b){var c=0,d=0,f=0,g=0;if(a=e(a)){b=e(b);d=a.offsetWidth;f=a.offsetHeight;if(a.getBoundingClientRect&&!(b||e.nodeIn(a,b))){b=a.getBoundingClientRect();g=K(e.nodeDoc(a));c=b.left+g.scrollX-g.left;g=b.top+g.scrollY-g.top}else for(;a&&a!=b;c+=a.offsetLeft||0,g+=a.offsetTop||0,a=a.offsetParent);}return{x:c,y:g,width:d,height:f}},nodeStyle:function(a,b,c,d){if(!b||e.isStr(b)){if(a=e(a)){c=a.style[b];
if(!c){c=V?e.nodeDoc(a).defaultView.getComputedStyle(a,j):a.currentStyle;if(b&&b=="float")b=ga;c=b?c[b]:c}}return c}a=A(a)?a:[a];for(d=a[i];d--;)(c=e(a[d]))&&u(c.style,b,function(f,g,h){if(g=="opacity"&&!V){h.zoom=1;h.filter=e.strSwap(h.filter||"",/alpha\([^)]*\)/i)+(f==1?"":"alpha(opacity="+f*100+")")}else if(g=="float"){h[ga]=f;return s}return k});return e},nodeClean:function(a,b,c,d,f){a=A(a)?a:[a];for(f=a[i];f--;)if(b=e(a[f]))for(c=b.firstChild;c;){d=c.nextSibling;c.nodeType==8||c.nodeType==3&&
!e.strTrim(c.nodeValue)?e.nodeDel(c):e.nodeClean(c);c=d}return e},nodeVal:function(a,b,c,d){if(arguments[i]==1)return(a=e(a))?q(a.tagName)=="li"||!(R in a)?a.innerHTML:a[R]:"";a=A(a)?a:[a];for(d=a[i];d--;)if(c=e(a[d]))c[q(c.tagName)!="li"&&R in c?R:"innerHTML"]=b+"";return e},nodeDel:function(a,b,c){a=A(a)?a:[a];for(c=a[i];c--;)(b=e(a[c]))&&b.parentNode&&b.parentNode.removeChild(b);return e},nodeClass:function(a,b,c,d,f,g,h,n){g=new X("(?:^|\\s+)"+b+"(?:\\s+|$)");a=A(a)?a:[a];n=a[i];for(h=e.isStr(c);n--;)if(f=
e(a[n])){d=f.className;f.className=e.strTrim(c||h?e.strSwap(d,g,h?" "+c+" ":" "):(d+=g.test(d)?"":" "+b))}return e},nodeIn:function(a,b,c){a=e(a);b=e(b);if(a&&b)if(a!=b)try{c=b.contains?b.contains(a):b.compareDocumentPosition(a)&16}catch(d){c=s}else c=k;return c},mouseInout:function(a,b,c){return(b=e.evt(b,c))?!e.nodeIn(b.relatedTarget||b[(/out$/.test(b.type)?"to":"from")+"Element"],a):s},startDrag:function(a,b,c,d){if((a=e(a))&&(d=e.evt(d))){e.clsPage();G=(G=d.touches)?G[0]:j;Y=e.evtPageXY(d);ea=
m(b);fa=b;Z=c;I=a;if(!V&&a.setCapture){Q.f=k;a.setCapture()}e.on(p,aa,y).on(p,Q,E).on(l,"blur",E).on(a,"losecapture",E).on(p,"keydown",O)}},on:function(a,b,c,d,f,g,h,n){if(m(c)){a=A(a)?a:[a];b=v(b)?b:[b];for(n=a[i];n--;)if(g=e(a[n]))for(h=b[i];h--;){!f&&(d?e.arrRemove:e.arrInsert)(T,[g,b[h],c]);if(g.addEventListener)d?g.removeEventListener(b[h],c,s):g.addEventListener(b[h],c,s);else if(g.attachEvent)d?g.detachEvent(x+b[h],c):g.attachEvent(x+b[h],c);else g[x+b[h]]=d?j:c}}return e},un:function(a,b,
c,d){return e.on(a,b,c,k,d)},evt:function(a,b,c,d,f){a=a||(b||l).event;if(!a){c=e.evt;d=32;try{for(;d--&&c.caller;)c=c.caller;if(e.isInsof(f=c.arguments[0],Event))a=f}catch(g){}}return a},evtCancel:function(a,b){if(a=e.evt(a,b))a.stopPropagation?a.stopPropagation():(a.cancelBubble=k)},evtPrevent:function(a,b){if(a=e.evt(a,b))a.preventDefault?a.preventDefault():(a.returnValue=s)},evtPageXY:function(a,b,c,d,f){if(a=e.evt(a,b)){d=a.targetTouches;if(!G&&d)f=d[d[i]-1];a=G||f||a;if(f=l.isNaN(a.pageX))d=
K();c={x:f?a.clientX+d.scrollX-d.left:a.pageX,y:f?a.clientY+d.scrollY-d.top:a.pageY}}else c={x:0,y:0};return c},evtTarget:function(a,b,c){if(a=e.evt(a,b))for(c=a.target||a.srcElement;c&&c.nodeType==3;)c=c.parentNode;return c},evtHitest:function(a,b){return(a=e.evt(a,b))?(b=a.touches)&&b[i]==1||a.which==1||!a.which&&a.button==1:s},evtClean:function(a){for(;a=T.pop();){a.push(k);e.un.apply(e,a);a[0]=j}$j=T=j},run:function(){U=U||new e.JS;U.run.apply(U,arguments)},invoke:function(a,b,c,d,f){d=H.call(arguments,
1);b=e.object(a,k);f=j;if(b){c=a.lastIndexOf(".");f=b.apply(e.object(a.substring(0,c),k),d)}return f},lock:function(a,b){if(!K[a]){K[a]=b;m(b)&&b()}},unlock:function(a){delete K[a]},XHR:e.clazz(e.Evt,{send:function(a,b,c,d,f){f=this;c=u({url:x,un:j,pw:j,timeout:3E4,start:o,fail:o,succ:o,done:o,data:"",method:a&&a.data?"POST":"GET",async:k},a);u(c,{_f:ha||(ha=function(g){try{this.fail(g)}catch(h){e.log(h,this.fail)}}),_e:ia||(ia=function(g){try{this.done(f.z)}catch(h){g=h}this._f(g)})});c[P]=u({"Content-Type":"application/x-www-form-urlencoded"},
c[P]);e.arrInsert(f.q||(f.q=[]),c,b?j:0);!f.z&&f.x()},x:function(a,b,c,d){a=this;if(b=a.q.pop()){b.start();if(!a.z)try{a.z=ka?new ka:new l.ActiveXObject("Microsoft.XMLHTTP")}catch(f){a.n();return b._e("unsupport")}a.v=r(function(){a.n();b._e("timeout");a.z.abort()},b.timeout);a.z.open(b.method,b.url,b.async,b.un,b.pw);for(c in b[P])a.z.setRequestHeader(c,b[P][c]);d=function(g){if(a.z.readyState==4&&(g=a.z.status)){a.n();try{b.done(a.z);/2\d{2}|304/.test(g)?b.succ(a.z):b.fail(g)}catch(h){b._f(h)}}};
if(b.async)a.z.onreadystatechange=d;a.z.send(b.data);b.async||d()}else a.stop()},n:function(a){a=this;a.c();a.w=r(a.x,50,s,a)},c:function(a,b,c){c=this;D(c.v);if(c.z)c.z.onreadystatechange=o;if(a){c.z&&c.z.abort();delete c.z}},stop:function(a,b){b=this;D(b.w);b.q=[];b.c(k);!a&&b.fireEvt("end")}}),TM:e.clazz({ctor:function(a,b){b=this;a=a||13;if(!W[a]){b.l=[];b.p=a;b.c=function(c){for(c=0;b.l[c];c++)try{b.l[c]()}catch(d){e.log(d,b.l[c])}};W[a]=b}return W[a]},on:function(a,b){b=this;b.l.push(a);if(!b.h)b.h=
r(b.c,b.p,k)},un:function(a,b){b=this;e.arrRemove(b.l,a);if(!b.l[i]){D(b.h);delete b.h}}}),FX:e.clazz(e.Evt,{ctor:function(a,b,c){c=this;if(!c.g||a){a=m(a)?a:na;c.g=function(d,f){return a(c.t,d,f-d,c.a)}}if(!c.z)c.z=new e.TM(b)},run:function(a,b,c,d,f){f=this;(f.q||(f.q=[])).push([a,b,d,c]);!f.m&&f.n()},n:function(a,b){a=this;if(a.o=b=a.q&&a.q.shift()){a.ctor(b[2]);a.c=m(b[1])?b[1]:o;a.a=b[0]||1E3;a.d=J();!a.m&&a.z.on(a.m=function(c){a.t=J()-a.d;if(a.t>a.a)c=a.t=a.a;try{a.c(a.g,a.o[3])}catch(d){e.log(c=
d,a.c)}c&&a.n()})}else a.stop()},stop:function(a,b){b=this;if(b.m&&b.z){b.z.un(b.m);delete b.m}!a&&b.fireEvt("end")}}),JS:e.clazz(e.Evt,{run:function(a,b){b=this;b.q||(b.q=[]);b.q.push(u({url:j,code:j,jsonp:j,start:o,done:o,timeout:3E4,charset:"UTF-8"},a));!b.m&&b.j()},j:function(a,b,c,d,f){b=this;a=b.q.shift();if(!b.m)b.m=p.documentElement;if(a){a.start();if(a.jsonp){a.x=e.id();e.JS[a.x]=function(){a.done.apply(a,arguments);a.x=j;D(a.g)}}if(y[a.url]){y[a.url]==k?r(a.done):y[a.url].push(a.done);r(b.j,
50,s,b)}else{if(a.url&&!a.jsonp)y[a.url]=[a.done];d=e("script",{type:"text/javascript",defer:"defer",id:f=e.id(),charset:a.charset});d.async=k;c=function(g){if(g!=i&&/(?:[4d]|te)$/.test(d.readyState))g=k;if(g){if(a.code)r(a.done);else if(a.jsonp)if(g!=k){e.JS[a.x]=o;a.done("timeout")}else{if(a.x)a.g=r(a.done,30,0,a,"fail")}else{for(;y[a.url][i];)r(y[a.url].shift(),0,0,a);y[a.url]=k}D(b._);D(b.$);d.onerror=d.onload=j;e.nodeDel(d);r(b.j,50,s,b)}};if(d.readyState)b._=r(c,50,k);d.onerror=d.onload=c;d[a.code?
"text":"src"]=a.code?a.code+';K("'+f+'").onload()':a.url+(a.x?[/\?/.test(a.url)?"&":"?",a.jsonp,"=K.JS.",a.x].join(""):"");b.m.insertBefore(d,b.m.firstChild);b.$=r(c,a.timeout,s,b,i)}}else{delete b.m;b.fireEvt("end")}}}),TP:{fix:function(a,b){return e.strSwap(a,[new X("("+(b?"":"\\\\|")+"')","g"),/"/g],["\\$1","&quot;"])},using:function(a,b,c,d){c=(d=e(a))?a:A[a]||(A[a]=e.id());M=[c,b].join("$");if(!N[M]){w=d?e.nodeVal(a):a;if((w=e.strSwap(w,/\s+/g," "))&&b){w=w.match(new X(e.strFormat("<{0}>([\\s\\S]*?)</{0}>",
b)));if(!w)throw"no tpl:"+b;w=w[1]}}return this},getFilled:function(a,b){a=a||{};try{if(N[M])b=N[M];else{b={s:"var _=[];_.push('"+e.strSwap(w,ba=ba||[/\s+/g,/<#/g,/;*#>/g,/\\(?=[^\r\n]*\n)/g,/\\/g,/\t/g,/'(?=[^\r\n]*\n)/g,/'/g,/\t/g,/\r=([^\n]+)\n/g,/\r/g,/\n/g,/([{;]);/g],ca=ca||[" ","\r","\n","\t","\\\\","\\","\t","\\'","'","',$1,'","');",";_.push('","$1"])+"');return _.join('')"};b.f=new Function(this.KEY,b.s);N[M]=b}w="";return b.f(a)}catch(c){return["ex:",c.message,"src:",e.strHTML(b.s)].join("")}},
toFill:function(a,b){e.nodeVal(a,this.getFilled(b))},KEY:"cx"}});l.K=e.on(l,"unload",e.evtClean)});
